apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: owuxc7ptz-go 
  janus-idp.io/tekton: owuxc7ptz-go
  backstage.io/kubernetes-id: owuxc7ptz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: owuxc7ptz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  